Fix error
src/components/Game.tsx(50,17): error TS2352: Conversion of type 'SuiParsedData' to type 'RawGameData' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type '{ dataType: "package"; disassembled: { [key: string]: unknown; }; }' is missing the following properties from type 'RawGameData': type, fields
src/components/Game.tsx(57,36): error TS2304: Cannot find name 'GameStatus'.
 ELIFECYCLE  Command failed with exit code 2.
Error: Command "pnpm run build" exited with 2